FROM node:20-alpine
ARG DB_URL
WORKDIR /app

COPY packages packages
COPY package-lock.json package-lock.json 
COPY package.json package.json
COPY turbo.json turbo.json 

COPY ./apps/ws-server ./apps/ws-server 

RUN npm install 
RUN DATABASE_URL=${DB_URL} npm run db:generate
RUN npm run build 

CMD [ "npm","run","start:wsserver" ]


