FROM node:20-alpine

WORKDIR /app
ARG DB_URL

COPY packages packages
COPY package-lock.json package-lock.json 
COPY package.json package.json
COPY turbo.json turbo.json 

COPY ./apps/http-server ./apps/http-server 

RUN npm install 
RUN DATABASE_URL=${DB_URL} npm run db:generate
RUN npm run build 

CMD [ "npm","run","start:http-server" ]

