name : backend deployment 
on : [push]
jobs:
  build: 
    runs-on : ubuntu-latest
    steps : 
      - uses: actions/checkout@v2

      - name : login into docker hub 
        uses : docker/login-action@v2
        with : 
          username : ${{secrets.DOCKERHUB_USERNAME}}
          password : ${{secrets.DOCKERHUB_TOKEN}}

      - name : build and push to docker hub
        uses : docker/build-push-action@v4
        with :
          context : . 
          file : ./Docker/Dockerfile.httpserver
          push : true
          build-args : 
            DB_URL=${{secrets.DATABASE_URL}}
          tags : ${{secrets.DOCKERHUB_USERNAME}}/monorepodeployment:${{github.sha}}
            
      - name : ssh into vm 
        uses : appleboy/ssh-action@v0.1.5
        with : 
          host : 52.53.160.84
          
          key : ${{secrets.PRIVATE_SECRET_KEY}}
          port : 22
          debug : true
          username : ubuntu
          script : | 
            docker stop httpserver 
            docker rm httpserver
            docker run -p 8000:8000 -d --name httpserver ${{secrets.DOCKERHUB_USERNAME}}/monorepodeployment:${{github.sha}}