name: Continuous Deployment Backend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Docker/Dockerfile.httpserver
          push: true
          build-args: | 
            DB_URL=${{secrets.DATABASE_URL}}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/monorepodeployment:${{ github.sha }}
      
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master

        with:
          host: 54.153.114.81
          username: ubuntu
          key: ${{ secrets.PRIVATE_SECRET_KEY }} 
          port: 22
          debug: true
          script: |
            docker stop httpserver
            docker rm httpserver
            docker run --name httpserver -d -p 8000:8000 ashishlakhimale/monorepodeployment:${{github.sha}}
               
            
