name : deployment through docker images 
on : [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:

    - name : login in docker 
      uses: docker/login-action@v2
      with :
        username : ${{secrets.DOCKERHUB_USERNAME}}
        password : ${{secrets.DOCKERHUB_TOKEN}}

    - name : build and push
      uses : docker/build-push-action@v4
      with : 
        context : .
        file : ./Docker/Dockerfile.httpserver 
        build-args : |
          DB_URL=${{secrets.DATABASE_URL}}
        tags : ${{secrets.DOCKERHUB_USERNAME}}/monorepodeployment:${{github.sha}}
      
    - name: ssh into the vm
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 13.52.243.227
        username: ubuntu
        key: ${{ secrets.PRIVATE_SECRET_KEY }}
        port: 22
        script: |
          docker stop httpserver
          docker rm httpserver
          docker run -p 8000:8000 --name httpserver -d ${{secrets.DOCKERHUB_USERNAME}}/monorepodeloyment:${{github.sha}}

  